language: rust
#dist: xenial

#cache deps
#cache: cargo

env:
  global:
    - CRATE_NAME=cargo-cache
    - RUST_BACKTRACE=full

matrix:
  fast_finish: false
  include:
# windows nightly
    - name: "windows nightly release"
      os: windows
      rust: nightly
      env: RELEASE="--release" EXE_SUFFIX=.exe

# osx nightly
    - name: "nightly osx release"
      os: osx
      rust: nightly
      env: RELEASE="--release"

# linux nightly
    - name: "nightly linux release"
      os: linux
      rust: nightly
      env: RELEASE="--release"

script:
  - cargo build --all ${RELEASE}

before_deploy:
  - ( cd target/release/ && tar -czf "$TRAVIS_BUILD_DIR"/"$CRATE_NAME"-"$TRAVIS_TAG"-"$TRAVIS_OS_NAME".tar.gz "${CRATE_NAME}${EXE_SUFFIX}" )

deploy:
- provider: releases
  # edge: true
  api_key: "$GITHUB_TOKEN"
  file_glob: true
  file: "$CRATE_NAME-$TRAVIS_TAG-$TRAVIS_OS_NAME.tar.gz"
  on:
    condition: $TRAVIS_RUST_VERSION = "nightly" && $RELEASE = "--release"
    tags: true
  skip_cleanup: true
